{{- if .Values.ingress.enabled -}}
{{- $svcPort := .Values.service.ports.http -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: {{ .Release.Name }}
          servicePort: {{ $svcPort }}
    host: {{ .Values.ingress.host }}
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ .Values.ingress.secret }}
{{- end -}}