kind: pipeline
type: kubernetes
name: release-develop

steps:
  - name: submodules
    image: alpine/git
    commands:
      - git submodule update --init --recursive
  - name: build
    image: plugins/docker
    settings:
      username:
        from_secret: registry_username
      password:
        from_secret: registry_password
      registry: registry.videocoin.net
      repo: registry.videocoin.net/cloud/videocoin-network
      build_args:
        - GA_TRACKING_ID=
        - AW_TRACKING_ID=
      tags:
        - ${DRONE_COMMIT_SHA}
  - name: deploy
    image: devth/helm:v3.1.1
    environment:
      KUBE_CONFIG:
        from_secret: dev_kube_config
    commands:
      - echo $KUBE_CONFIG | base64 -d > kube.config
      - helm --kubeconfig=kube.config upgrade -i --wait --set image.tag=$DRONE_COMMIT_SHA -n console videocoin-network ./deploy/helm

trigger:
  event:
    - push
    - pull_request
  branch:
    - drone
    - infra


---
kind: pipeline
type: kubernetes
name: helm-push

steps:
  - name: lint-chart
    image: pelotech/drone-helm3
    settings:
      mode: lint
      chart: ./deploy/helm
  - name: publish-chart
    image: devth/helm:v3.1.1
    environment:
      USERNAME:
        from_secret: registry_username
      PASSWORD:
        from_secret: registry_password
    commands:
      - helm repo add console https://registry.videocoin.net/chartrepo/cloud --username $$USERNAME --password $$PASSWORD
      - helm plugin install https://github.com/chartmuseum/helm-push
      - helm push ./deploy/helm console --username $$USERNAME --password $$PASSWORD

trigger:
  event:
    - push
  branch:
    - infra
