replicasCount: 1
maxUnavailableCount: 0

image:
  repository: registry.videocoin.net/cloud/videocoin-network
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets: 
  - name: regcred

service:
  ports:
    http: 80

serviceAccount:
  name: default

resources:
  limits:
    cpu: 100m
    memory: 64Mi
  requests:
    cpu: 10m
    memory: 16Mi

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns-prod
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: dev.videocoin.network
      paths:
        - /
  tls:
    - secretName: tls-cert-dev-videocoin-network
      hosts:
        - dev.videocoin.network

config:
  nginx.conf: |
    events {
        worker_connections 1024;
    }

    http {
        include /etc/nginx/mime.types;

        server {
            listen 80;
            server_name localhost;
            root /usr/share/nginx/html;

            location / {
              root   /usr/share/nginx/html;
              index  index.html index.htm;
              try_files $uri $uri/ index.html;
            }

            location ~* ^.+\.(?:css|cur|js|jpe?g|gif|htc|ico|png|html|xml|otf|ttf|eot|woff|woff2|svg|webp)$ {
                access_log off;
                expires 30d;
                add_header Cache-Control public;
            }
        }
    }
